[build]
  publish = ".build"
  command = "gulp default"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options: ALLOWALL
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"

[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "max-age=604800, public, stale-while-revalidate=5"

[[headers]]
  for = "/assets/img/*"
  [headers.values]
    Cache-Control = "max-age=604800, public, stale-while-revalidate=5"
